# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sub_title',
            new_name='subtitle',
        ),
    ]
