# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_auto_20160930_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Education Title'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Experience Title'),
        ),
    ]
