# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0004_auto_20160930_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='education_title',
            new_name='education_subtitle',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='experience_title',
            new_name='experience_subtitle',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_title',
            new_name='profile_subtitle',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_address',
            field=models.CharField(max_length=100, null=True, verbose_name='Contact Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Contact E-mail'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_subtitle',
            field=models.CharField(max_length=100, null=True, verbose_name='Contact Title'),
        ),
    ]
