# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0006_auto_20160930_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_subtitle',
            field=models.CharField(max_length=100, null=True, verbose_name='Contact Subtitle'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_subtitle',
            field=models.CharField(max_length=100, null=True, verbose_name='Education Subtitle'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience_subtitle',
            field=models.CharField(max_length=100, null=True, verbose_name='Experience Subtitle'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_subtitle',
            field=models.CharField(max_length=100, verbose_name='Profile Subtitle'),
        ),
    ]
