# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-12 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0008_auto_20160930_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('link', models.URLField(verbose_name='URL')),
                ('icon', models.CharField(max_length=30, verbose_name='Icon')),
                ('order', models.IntegerField(blank=True, default=1, verbose_name='Order')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='curriculo.Profile')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
